# Generated by Django 2.2.10 on 2020-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_tasklist_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='owner',
            new_name='manage',
        ),
    ]
